//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYLOG
    {
        public int LOGID { get; set; }
        public long SYSTEM_ID { get; set; }
        public int LOGTYPE { get; set; }
        public string MESSAGE { get; set; }
        public string USERID { get; set; }
        public string MAC { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual LOGTYPE LOGTYPE1 { get; set; }
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    }
}
