//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDRESS { get; set; }
        public string COUNTRY { get; set; }
        public int INDUSTRY_ID { get; set; }
        public Nullable<int> NUMBER_OF_EMPLOYEES { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public string CONTACT_NUMBER_PERSON_IM { get; set; }
    }
}
