//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEPRIV
    {
        public int ID { get; set; }
        public int ROLEID { get; set; }
        public int PRIVID { get; set; }
    
        public virtual PRIV PRIV { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
