//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLE()
        {
            this.ROLEPRIVS = new HashSet<ROLEPRIV>();
            this.USERROLES = new HashSet<USERROLE>();
        }
    
        public int ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public int CREATEDBY { get; set; }
        public int LASTMODIFIED { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public long ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLEPRIV> ROLEPRIVS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERROLE> USERROLES { get; set; }
    }
}
