//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORT
    {
        public long TICKET_ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public int USERID { get; set; }
        public string SUBJECT { get; set; }
        public string DISCRIPTION { get; set; }
        public string MODULE { get; set; }
        public string URGENCY { get; set; }
        public bool STATUS { get; set; }
        public int CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public int ASSIGNED_TO { get; set; }
    
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
        public virtual USER_LOGIN USER_LOGIN { get; set; }
    }
}
