//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_PROCESSOR_USAGE
    {
        public long ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public int USER_ID { get; set; }
        public string USAGE { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
    
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    }
}
