//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_PRINTER
    {
        public long ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public string CAPABILITY_DESCRIPTION { get; set; }
        public Nullable<int> AVERAGE_PAGES_PER_MINUTE { get; set; }
        public string CAPTION { get; set; }
        public string DEVICE_ID { get; set; }
        public string NAME { get; set; }
        public string PAPER_SIZE_SUPPORTED { get; set; }
        public string PRINTER_PAPER_NAME { get; set; }
        public Nullable<bool> NETWORK { get; set; }
        public string PRINT_PROCESSOR { get; set; }
        public Nullable<bool> SPOOL_ENABLED { get; set; }
        public Nullable<int> HORIZONTAL_RESOLUTION { get; set; }
        public Nullable<int> VERTICAL_RESOLUTION { get; set; }
        public string SYSTEM_NAME { get; set; }
        public string STATUS { get; set; }
    
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    }
}
