//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_LICENSE_KEY
    {
        public int LICENSE_ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public System.DateTime PURCHASE_DATE { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
        public int QTY { get; set; }
        public int EDITION { get; set; }
        public int SUPPORT { get; set; }
    
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    }
}
