//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_INFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTEM_INFORMATION()
        {
            this.ACTIVITYLOGs = new HashSet<ACTIVITYLOG>();
            this.BROWSER_HISTORY = new HashSet<BROWSER_HISTORY>();
            this.SUPPORTs = new HashSet<SUPPORT>();
            this.SYSTEM_DEVICE = new HashSet<SYSTEM_DEVICE>();
            this.SYSTEM_INSTALLED_APPLICATION = new HashSet<SYSTEM_INSTALLED_APPLICATION>();
            this.SYSTEM_LICENSE_KEY = new HashSet<SYSTEM_LICENSE_KEY>();
            this.SYSTEM_MEMORY_SIZE = new HashSet<SYSTEM_MEMORY_SIZE>();
            this.SYSTEM_MEMORY = new HashSet<SYSTEM_MEMORY>();
            this.SYSTEM_MEMORY_USAGE = new HashSet<SYSTEM_MEMORY_USAGE>();
            this.SYSTEM_NETWORK = new HashSet<SYSTEM_NETWORK>();
            this.SYSTEM_POINTING_DEVICE = new HashSet<SYSTEM_POINTING_DEVICE>();
            this.SYSTEM_PORT_CONNECTOR = new HashSet<SYSTEM_PORT_CONNECTOR>();
            this.SYSTEM_PRINTER = new HashSet<SYSTEM_PRINTER>();
            this.SYSTEM_PROCESSOR_USAGE = new HashSet<SYSTEM_PROCESSOR_USAGE>();
            this.SYSTEM_SOUND_DEVICE = new HashSet<SYSTEM_SOUND_DEVICE>();
            this.SYSTEM_USERS = new HashSet<SYSTEM_USERS>();
            this.SYSTEM_VIDEO_CONTROLLER = new HashSet<SYSTEM_VIDEO_CONTROLLER>();
            this.SYSTEM_VOLUME = new HashSet<SYSTEM_VOLUME>();
            this.WINDOW_ACTIVE = new HashSet<WINDOW_ACTIVE>();
        }
    
        public long SYSTEM_ID { get; set; }
        public string PROCESSOR_ID { get; set; }
        public string HDD_SERIAL_NO { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string MOTHERBOARD_MANUFACTURER { get; set; }
        public string MOTHERBOARD_PRODUCT_ID { get; set; }
        public string CD_DVD_DRIVE_PATH { get; set; }
        public string BIOS_MAKER { get; set; }
        public string BIOS_SERIAL_NO { get; set; }
        public string BIOS_CAPTION { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string PHYSICAL_RAM_MEMORY { get; set; }
        public string RAM_SLOT_ON_MOTHERBOARD { get; set; }
        public string CPU_MANUFACTURER { get; set; }
        public string CPU_CURRENT_CLOCK_SPEED { get; set; }
        public string DEFAULT_IP_GATEWAY { get; set; }
        public string CPU_SPEED_IN_GHZ { get; set; }
        public string CURRENT_LANGUAGE { get; set; }
        public string OS_INFORMATION { get; set; }
        public string PROCESSOR_INFORMATION { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string OS_LICENSE { get; set; }
        public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
        public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
        public int USERID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITYLOG> ACTIVITYLOGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BROWSER_HISTORY> BROWSER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPORT> SUPPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_DEVICE> SYSTEM_DEVICE { get; set; }
        public virtual USER_LOGIN USER_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_INSTALLED_APPLICATION> SYSTEM_INSTALLED_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_LICENSE_KEY> SYSTEM_LICENSE_KEY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_MEMORY_SIZE> SYSTEM_MEMORY_SIZE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_MEMORY> SYSTEM_MEMORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_MEMORY_USAGE> SYSTEM_MEMORY_USAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_NETWORK> SYSTEM_NETWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_POINTING_DEVICE> SYSTEM_POINTING_DEVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_PORT_CONNECTOR> SYSTEM_PORT_CONNECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_PRINTER> SYSTEM_PRINTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_PROCESSOR_USAGE> SYSTEM_PROCESSOR_USAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_SOUND_DEVICE> SYSTEM_SOUND_DEVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_USERS> SYSTEM_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_VIDEO_CONTROLLER> SYSTEM_VIDEO_CONTROLLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEM_VOLUME> SYSTEM_VOLUME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WINDOW_ACTIVE> WINDOW_ACTIVE { get; set; }
    }
}
