//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_MEMORY
    {
        public long ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public string ATTRIBUTES { get; set; }
        public string BANK_LABEL { get; set; }
        public long CAPACITY { get; set; }
        public string CAPTION { get; set; }
        public long CONFIGURE_CLOCL_SPEED { get; set; }
        public string CREATION_CLASS_NAME { get; set; }
        public Nullable<int> DATA_WIDTH { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEVICE_LOCATOR { get; set; }
        public Nullable<int> FORM_FACTOR { get; set; }
        public Nullable<int> INTER_LEAVE_DATA_DEPTH { get; set; }
        public string INTER_LEAVE_POSITION { get; set; }
        public string MANUFACTURER { get; set; }
        public string SERIAL_NO { get; set; }
        public string SPEED { get; set; }
        public Nullable<int> TOTAL_WIDTH { get; set; }
        public Nullable<int> TYPE_DETAIL { get; set; }
        public Nullable<int> MEMORY_TYPE { get; set; }
        public string NAME { get; set; }
        public string PART_NUMBER { get; set; }
        public Nullable<int> POSITION_IN_ROW { get; set; }
        public Nullable<int> SMBIOS_MEMORY_TYPE { get; set; }
    
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    }
}
