//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BROWSER_HISTORY
    {
        public long ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public string URL { get; set; }
        public string TITLE { get; set; }
        public Nullable<long> VISIT_COUNT { get; set; }
        public string LAST_VISIT_TIME { get; set; }
        public string LAST_VISIT_DATE { get; set; }
        public Nullable<int> BROSWER_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
