//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_INFOR_REGISTERED
    {
        public long SYSTEM_ID { get; set; }
        public string PROCESSOR_ID { get; set; }
        public string HDD_SERIAL_NO { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string MOTHERBOARD_MANUFACTURER { get; set; }
        public string MOTHERBOARD_PRODUCT_ID { get; set; }
        public string CD_DVD_DRIVE_PATH { get; set; }
        public string BIOS_MAKER { get; set; }
        public string BIOS_SERIAL_NO { get; set; }
        public string BIOS_CAPTION { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string PHYSICAL_RAM_MEMORY { get; set; }
        public string RAM_SLOT_ON_MOTHERBOARD { get; set; }
        public string CPU_MANUFACTURER { get; set; }
        public string CPU_CURRENT_CLOCK_SPEED { get; set; }
        public string DEFAULT_IP_GATEWAY { get; set; }
        public string CPU_SPEED_IN_GHZ { get; set; }
        public string CURRENT_LANGUAGE { get; set; }
        public string OS_INFORMATION { get; set; }
        public string PROCESSOR_INFORMATION { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string OS_LICENSE { get; set; }
        public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
        public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
        public int USERID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string USER_NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FK_LICENSE__ID { get; set; }
        public string LIC_NAME { get; set; }
        public string DEVICE_MAC { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
    }
}
