//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_NETWOR_DEVICES
    {
        public long SYSTEM_ID { get; set; }
        public long ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
        public string STATUS { get; set; }
        public string SPEED { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string DEFAULT_IP_GATEWAY { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
        public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
        public int USERID { get; set; }
    }
}
