//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_MEMORY
    {
        public long ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public int USER_ID { get; set; }
        public string ATTRIBUTES { get; set; }
        public string BANK_LABEL { get; set; }
        public long CAPACITY { get; set; }
        public string CAPTION { get; set; }
        public long CONFIGURE_CLOCL_SPEED { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEVICE_LOCATOR { get; set; }
        public string MANUFACTURER { get; set; }
        public string SERIAL_NO { get; set; }
        public string SPEED { get; set; }
        public string NAME { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
        public string LOGIN_NAME { get; set; }
    }
}
