//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_REGISTERED_APPS
    {
        public long ID { get; set; }
        public string APP_NAME { get; set; }
        public long SIZE { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string DEFAULT_IP_GATEWAY { get; set; }
        public string COMPUTER_NAME { get; set; }
        public int USERID { get; set; }
        public string MOTHERBOARD_MANUFACTURER { get; set; }
        public long SYSTEM_ID { get; set; }
    }
}
