//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_VOLUME
    {
        public int Expr1 { get; set; }
        public long SYETEM_ID { get; set; }
        public string DEVICE_TYPE { get; set; }
        public string CAPTION { get; set; }
        public string SERIAL_NO { get; set; }
        public string TOTAL { get; set; }
        public string FREE { get; set; }
        public string USED { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
        public int USER_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string COMPANY { get; set; }
    }
}
