//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_PRINTER_INFORMATION
    {
        public long ID { get; set; }
        public long SYSTEM_ID { get; set; }
        public string CAPTION { get; set; }
        public string NAME { get; set; }
        public Nullable<int> HORIZONTAL_RESOLUTION { get; set; }
        public Nullable<int> VERTICAL_RESOLUTION { get; set; }
        public Nullable<bool> NETWORK { get; set; }
        public string PRINTER_PAPER_NAME { get; set; }
        public string PAPER_SIZE_SUPPORTED { get; set; }
        public string SYSTEM_NAME { get; set; }
        public string STATUS { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
        public int USER_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string COMPANY { get; set; }
        public int USERID { get; set; }
    }
}
