//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYSTEM_ACTIVE_WINDOW
    {
        public int ID { get; set; }
        public string WINDOW_TITLE { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
        public string WIN_PROCESS { get; set; }
        public string WINDOW_URL { get; set; }
        public Nullable<long> VISIT_COUNT { get; set; }
        public long SECONDS { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string COMPUTER_NAME { get; set; }
        public long SYSTEM_ID { get; set; }
        public int USER_ID { get; set; }
        public string LOGIN_NAME { get; set; }
    }
}
