//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_PRIVS_WITHROLE
    {
        public int PRIVID { get; set; }
        public string DEFAULTNAME { get; set; }
        public string DEFUULTTEXT { get; set; }
        public bool STATUS { get; set; }
        public string ROLENAME { get; set; }
        public int ROLEID { get; set; }
        public int USER_ID { get; set; }
    }
}
