//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpyAndStealService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINDOW_ACTIVE
    {
        public int ID { get; set; }
        public Nullable<long> SYSTEM_ID { get; set; }
        public string WINDOW_TITLE { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string WIN_PROCESS { get; set; }
        public string WINDOW_URL { get; set; }
        public Nullable<long> VISIT_COUNT { get; set; }
        public long SECONDS { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
    
        public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    }
}
