//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVITYLOG
{
    public int LOGID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int LOGTYPE { get; set; }
    public string MESSAGE { get; set; }
    public string USERID { get; set; }
    public string MAC { get; set; }
    public Nullable<System.DateTime> DATE { get; set; }

    public virtual LOGTYPE LOGTYPE1 { get; set; }
    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class BROWSER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BROWSER()
    {
        this.BROWSER_HISTORY = new HashSet<BROWSER_HISTORY>();
    }

    public int ID { get; set; }
    public string NAME { get; set; }
    public string DESCRIPTION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BROWSER_HISTORY> BROWSER_HISTORY { get; set; }
}

public partial class BROWSER_HISTORY
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string URL { get; set; }
    public string TITLE { get; set; }
    public Nullable<long> VISIT_COUNT { get; set; }
    public string LAST_VISIT_TIME { get; set; }
    public string LAST_VISIT_DATE { get; set; }
    public Nullable<int> BROSWER_ID { get; set; }

    public virtual BROWSER BROWSER { get; set; }
    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class COMPANY
{
    public long ID { get; set; }
    public string NAME { get; set; }
    public string DESCRIPTION { get; set; }
    public string ADDRESS { get; set; }
    public string COUNTRY { get; set; }
    public int INDUSTRY_ID { get; set; }
    public Nullable<int> NUMBER_OF_EMPLOYEES { get; set; }
    public string PHONE { get; set; }
    public string EMAIL { get; set; }
    public string WEB { get; set; }
    public string CONTACT_NUMBER_PERSON_IM { get; set; }
}

public partial class COMPANY_INDUSTRY
{
    public int ID { get; set; }
    public string DESCRIPTION { get; set; }
}

public partial class LICENSE_TYPE
{
    public int ID { get; set; }
    public string NAME { get; set; }
    public string DESCRIPTION { get; set; }
    public int LIMIT { get; set; }
    public System.DateTime TIME_STAMP { get; set; }
}

public partial class LOGTYPE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LOGTYPE()
    {
        this.ACTIVITYLOGs = new HashSet<ACTIVITYLOG>();
    }

    public int LOGTYPEID { get; set; }
    public string LOGTEXT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ACTIVITYLOG> ACTIVITYLOGs { get; set; }
}

public partial class PRIV
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRIV()
    {
        this.ROLEPRIVS = new HashSet<ROLEPRIV>();
    }

    public int PRIVID { get; set; }
    public string DEFAULTNAME { get; set; }
    public string DEFUULTTEXT { get; set; }
    public bool STATUS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ROLEPRIV> ROLEPRIVS { get; set; }
}

public partial class ROLE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ROLE()
    {
        this.ROLEPRIVS = new HashSet<ROLEPRIV>();
        this.USERROLES = new HashSet<USERROLE>();
    }

    public int ROLEID { get; set; }
    public string ROLENAME { get; set; }
    public System.DateTime CREATEDDATE { get; set; }
    public int CREATEDBY { get; set; }
    public int LASTMODIFIED { get; set; }
    public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
    public long ISACTIVE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ROLEPRIV> ROLEPRIVS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USERROLE> USERROLES { get; set; }
}

public partial class ROLEPRIV
{
    public int ID { get; set; }
    public int ROLEID { get; set; }
    public int PRIVID { get; set; }

    public virtual PRIV PRIV { get; set; }
    public virtual ROLE ROLE { get; set; }
}

public partial class SUPPORT
{
    public long TICKET_ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USERID { get; set; }
    public string SUBJECT { get; set; }
    public string DISCRIPTION { get; set; }
    public string MODULE { get; set; }
    public string URGENCY { get; set; }
    public bool STATUS { get; set; }
    public int CREATED_BY { get; set; }
    public Nullable<System.DateTime> CREATED_DATE { get; set; }
    public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    public int ASSIGNED_TO { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    public virtual USER_LOGIN USER_LOGIN { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class SYSTEM_DEVICE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string DEVICE_ID { get; set; }
    public int DEVICE_TYPE { get; set; }
    public string DESCRIPTION { get; set; }
    public System.DateTime TIME_STAMP { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_INFORMATION
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SYSTEM_INFORMATION()
    {
        this.ACTIVITYLOGs = new HashSet<ACTIVITYLOG>();
        this.BROWSER_HISTORY = new HashSet<BROWSER_HISTORY>();
        this.SUPPORTs = new HashSet<SUPPORT>();
        this.SYSTEM_DEVICE = new HashSet<SYSTEM_DEVICE>();
        this.SYSTEM_INSTALLED_APPLICATION = new HashSet<SYSTEM_INSTALLED_APPLICATION>();
        this.SYSTEM_LICENSE_KEY = new HashSet<SYSTEM_LICENSE_KEY>();
        this.SYSTEM_MEMORY_SIZE = new HashSet<SYSTEM_MEMORY_SIZE>();
        this.SYSTEM_MEMORY = new HashSet<SYSTEM_MEMORY>();
        this.SYSTEM_MEMORY_USAGE = new HashSet<SYSTEM_MEMORY_USAGE>();
        this.SYSTEM_NETWORK = new HashSet<SYSTEM_NETWORK>();
        this.SYSTEM_POINTING_DEVICE = new HashSet<SYSTEM_POINTING_DEVICE>();
        this.SYSTEM_PORT_CONNECTOR = new HashSet<SYSTEM_PORT_CONNECTOR>();
        this.SYSTEM_PRINTER = new HashSet<SYSTEM_PRINTER>();
        this.SYSTEM_PROCESSOR_USAGE = new HashSet<SYSTEM_PROCESSOR_USAGE>();
        this.SYSTEM_SOUND_DEVICE = new HashSet<SYSTEM_SOUND_DEVICE>();
        this.SYSTEM_USERS = new HashSet<SYSTEM_USERS>();
        this.SYSTEM_VIDEO_CONTROLLER = new HashSet<SYSTEM_VIDEO_CONTROLLER>();
        this.SYSTEM_VOLUME = new HashSet<SYSTEM_VOLUME>();
        this.WINDOW_ACTIVE = new HashSet<WINDOW_ACTIVE>();
    }

    public long SYSTEM_ID { get; set; }
    public string PROCESSOR_ID { get; set; }
    public string HDD_SERIAL_NO { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string MOTHERBOARD_MANUFACTURER { get; set; }
    public string MOTHERBOARD_PRODUCT_ID { get; set; }
    public string CD_DVD_DRIVE_PATH { get; set; }
    public string BIOS_MAKER { get; set; }
    public string BIOS_SERIAL_NO { get; set; }
    public string BIOS_CAPTION { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string PHYSICAL_RAM_MEMORY { get; set; }
    public string RAM_SLOT_ON_MOTHERBOARD { get; set; }
    public string CPU_MANUFACTURER { get; set; }
    public string CPU_CURRENT_CLOCK_SPEED { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string CPU_SPEED_IN_GHZ { get; set; }
    public string CURRENT_LANGUAGE { get; set; }
    public string OS_INFORMATION { get; set; }
    public string PROCESSOR_INFORMATION { get; set; }
    public string COMPUTER_NAME { get; set; }
    public string OS_LICENSE { get; set; }
    public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USERID { get; set; }
    public Nullable<int> COMPANY_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ACTIVITYLOG> ACTIVITYLOGs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BROWSER_HISTORY> BROWSER_HISTORY { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SUPPORT> SUPPORTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_DEVICE> SYSTEM_DEVICE { get; set; }
    public virtual USER_LOGIN USER_LOGIN { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_INSTALLED_APPLICATION> SYSTEM_INSTALLED_APPLICATION { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_LICENSE_KEY> SYSTEM_LICENSE_KEY { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_MEMORY_SIZE> SYSTEM_MEMORY_SIZE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_MEMORY> SYSTEM_MEMORY { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_MEMORY_USAGE> SYSTEM_MEMORY_USAGE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_NETWORK> SYSTEM_NETWORK { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_POINTING_DEVICE> SYSTEM_POINTING_DEVICE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_PORT_CONNECTOR> SYSTEM_PORT_CONNECTOR { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_PRINTER> SYSTEM_PRINTER { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_PROCESSOR_USAGE> SYSTEM_PROCESSOR_USAGE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_SOUND_DEVICE> SYSTEM_SOUND_DEVICE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_USERS> SYSTEM_USERS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_VIDEO_CONTROLLER> SYSTEM_VIDEO_CONTROLLER { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_VOLUME> SYSTEM_VOLUME { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WINDOW_ACTIVE> WINDOW_ACTIVE { get; set; }
}

public partial class SYSTEM_INSTALLED_APPLICATION
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string APP_NAME { get; set; }
    public long SIZE { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_LICENSE_KEY
{
    public int LICENSE_ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public System.DateTime PURCHASE_DATE { get; set; }
    public System.DateTime EXPIRE_DATE { get; set; }
    public int QTY { get; set; }
    public int EDITION { get; set; }
    public int SUPPORT { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_MEMORY
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string ATTRIBUTES { get; set; }
    public string BANK_LABEL { get; set; }
    public long CAPACITY { get; set; }
    public string CAPTION { get; set; }
    public long CONFIGURE_CLOCL_SPEED { get; set; }
    public string CREATION_CLASS_NAME { get; set; }
    public Nullable<int> DATA_WIDTH { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_LOCATOR { get; set; }
    public Nullable<int> FORM_FACTOR { get; set; }
    public Nullable<int> INTER_LEAVE_DATA_DEPTH { get; set; }
    public string INTER_LEAVE_POSITION { get; set; }
    public string MANUFACTURER { get; set; }
    public string SERIAL_NO { get; set; }
    public string SPEED { get; set; }
    public Nullable<int> TOTAL_WIDTH { get; set; }
    public Nullable<int> TYPE_DETAIL { get; set; }
    public Nullable<int> MEMORY_TYPE { get; set; }
    public string NAME { get; set; }
    public string PART_NUMBER { get; set; }
    public Nullable<int> POSITION_IN_ROW { get; set; }
    public Nullable<int> SMBIOS_MEMORY_TYPE { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_MEMORY_SIZE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int MEMORY_TYPE { get; set; }
    public string TOTAL { get; set; }
    public string FREE { get; set; }
    public string USED { get; set; }
    public System.DateTime TIME_STAMP { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_MEMORY_USAGE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USER_ID { get; set; }
    public string USAGE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_NETWORK
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string DESCRIPTION { get; set; }
    public string NAME { get; set; }
    public Nullable<System.DateTime> TIME_STAMP { get; set; }
    public string STATUS { get; set; }
    public string SPEED { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_POINTING_DEVICE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_ID { get; set; }
    public string DEVICE_INTERFACE { get; set; }
    public string HARDWARE_TYPE { get; set; }
    public string MANUFACTURER { get; set; }
    public string NAME { get; set; }
    public Nullable<int> NUMBER_OF_BUTTONS { get; set; }
    public string SYSTEM_NAME { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_PORT_CONNECTOR
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string CONNECTOR_TYPE { get; set; }
    public string DESCRIPTION { get; set; }
    public string NAME { get; set; }
    public string TAG { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_PRINTER
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPABILITY_DESCRIPTION { get; set; }
    public Nullable<int> AVERAGE_PAGES_PER_MINUTE { get; set; }
    public string CAPTION { get; set; }
    public string DEVICE_ID { get; set; }
    public string NAME { get; set; }
    public string PAPER_SIZE_SUPPORTED { get; set; }
    public string PRINTER_PAPER_NAME { get; set; }
    public Nullable<bool> NETWORK { get; set; }
    public string PRINT_PROCESSOR { get; set; }
    public Nullable<bool> SPOOL_ENABLED { get; set; }
    public Nullable<int> HORIZONTAL_RESOLUTION { get; set; }
    public Nullable<int> VERTICAL_RESOLUTION { get; set; }
    public string SYSTEM_NAME { get; set; }
    public string STATUS { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_PROCESSOR_USAGE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USER_ID { get; set; }
    public string USAGE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_SOUND_DEVICE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_ID { get; set; }
    public string MANUFACTURER { get; set; }
    public string NAME { get; set; }
    public string STATUS_INFO { get; set; }
    public string SYSTEM_NAME { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_USERS
{
    public long ID { get; set; }
    public int USER_ID { get; set; }
    public long SYSTEM_ID { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
    public virtual USER_LOGIN USER_LOGIN { get; set; }
}

public partial class SYSTEM_VIDEO_CONTROLLER
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string ADAPTER_COMPATIABILITY { get; set; }
    public string ADAPTER_DAC_TYPE { get; set; }
    public string ADAPTER_AVAILABILITY { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_ID { get; set; }
    public Nullable<System.DateTime> DRIVER_DATE { get; set; }
    public string DRIVER_VERSION { get; set; }
    public string NAME { get; set; }
    public string VIDEO_ARCHITECTURE { get; set; }
    public string VIDEO_MEMORY_TYPE { get; set; }
    public string VIDEO_PROCESSOR { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class SYSTEM_VOLUME
{
    public int ID { get; set; }
    public long SYETEM_ID { get; set; }
    public string DEVICE_TYPE { get; set; }
    public string CAPTION { get; set; }
    public string SERIAL_NO { get; set; }
    public string TOTAL { get; set; }
    public string FREE { get; set; }
    public string USED { get; set; }
    public System.DateTime TIME_STAMP { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}

public partial class USER_LOGIN
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USER_LOGIN()
    {
        this.SUPPORTs = new HashSet<SUPPORT>();
        this.SYSTEM_INFORMATION = new HashSet<SYSTEM_INFORMATION>();
        this.SYSTEM_USERS = new HashSet<SYSTEM_USERS>();
        this.USERPRIVS = new HashSet<USERPRIV>();
    }

    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string PASSWORD { get; set; }
    public string EMAIL { get; set; }
    public Nullable<int> USER_ROLE { get; set; }
    public Nullable<bool> STATUS { get; set; }
    public string COMPANY { get; set; }
    public string FIRST_NAME { get; set; }
    public string LAST_NAME { get; set; }
    public string PHONE { get; set; }
    public Nullable<System.DateTime> LAST_LOGIN { get; set; }
    public bool EMAIL_ALERT { get; set; }
    public bool SMS_ALERT { get; set; }
    public bool PHONE_ALERT { get; set; }
    public string ADDRESS_LINE_1 { get; set; }
    public string ADDRESS_LINE_2 { get; set; }
    public string STATE { get; set; }
    public string CITY { get; set; }
    public string PINCODE { get; set; }
    public string COUNTRY { get; set; }
    public Nullable<int> FK_COMPANY_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SUPPORT> SUPPORTs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_INFORMATION> SYSTEM_INFORMATION { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SYSTEM_USERS> SYSTEM_USERS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USERPRIV> USERPRIVS { get; set; }
}

public partial class USERPRIV
{
    public int ID { get; set; }
    public int USERID { get; set; }
    public int PRIV { get; set; }
    public int STATUS { get; set; }

    public virtual USER_LOGIN USER_LOGIN { get; set; }
}

public partial class USERROLE
{
    public int ID { get; set; }
    public int ROLEID { get; set; }
    public int USERID { get; set; }

    public virtual ROLE ROLE { get; set; }
}

public partial class V_BrowerHistoryAll
{
    public string Brower { get; set; }
    public string URL { get; set; }
    public string TITLE { get; set; }
    public Nullable<long> VISIT_COUNT { get; set; }
    public string LAST_VISIT_TIME { get; set; }
    public string LAST_VISIT_DATE { get; set; }
    public long SYSTEM_ID { get; set; }
    public string DESCRIPTION { get; set; }
    public string MAC_ADDRESS { get; set; }
}

public partial class V_BROWSER_HISTORY
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string URL { get; set; }
    public string TITLE { get; set; }
    public Nullable<long> VISIT_COUNT { get; set; }
    public string LAST_VISIT_TIME { get; set; }
    public string LAST_VISIT_DATE { get; set; }
    public Nullable<int> BROSWER_ID { get; set; }
    public string NAME { get; set; }
    public string DESCRIPTION { get; set; }
}

public partial class V_ROLE_PRIV
{
    public bool STATUS { get; set; }
    public int ROLEID { get; set; }
    public int PRIVID { get; set; }
    public string DEFAULTNAME { get; set; }
    public string DEFUULTTEXT { get; set; }
    public string ROLENAME { get; set; }
    public long ISACTIVE { get; set; }
}

public partial class V_SYSTEM_ACTIVE_WINDOW
{
    public int ID { get; set; }
    public string WINDOW_TITLE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }
    public string WIN_PROCESS { get; set; }
    public string WINDOW_URL { get; set; }
    public Nullable<long> VISIT_COUNT { get; set; }
    public long SECONDS { get; set; }
    public Nullable<System.DateTime> START_TIME { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string COMPUTER_NAME { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
}

public partial class V_SYSTEM_ACTIVE_WINDOWS
{
    public string WINDOW_TITLE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }
    public string WINDOW_URL { get; set; }
    public Nullable<long> VISIT_COUNT { get; set; }
    public long SECONDS { get; set; }
    public Nullable<System.DateTime> START_TIME { get; set; }
    public Nullable<long> SYSTEM_ID { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string MOTHERBOARD_MANUFACTURER { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string COMPUTER_NAME { get; set; }
    public int USERID { get; set; }
    public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
}

public partial class V_SYSTEM_INFOR_REGISTERED
{
    public long SYSTEM_ID { get; set; }
    public string PROCESSOR_ID { get; set; }
    public string HDD_SERIAL_NO { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string MOTHERBOARD_MANUFACTURER { get; set; }
    public string MOTHERBOARD_PRODUCT_ID { get; set; }
    public string CD_DVD_DRIVE_PATH { get; set; }
    public string BIOS_MAKER { get; set; }
    public string BIOS_SERIAL_NO { get; set; }
    public string BIOS_CAPTION { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string PHYSICAL_RAM_MEMORY { get; set; }
    public string RAM_SLOT_ON_MOTHERBOARD { get; set; }
    public string CPU_MANUFACTURER { get; set; }
    public string CPU_CURRENT_CLOCK_SPEED { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string CPU_SPEED_IN_GHZ { get; set; }
    public string CURRENT_LANGUAGE { get; set; }
    public string OS_INFORMATION { get; set; }
    public string PROCESSOR_INFORMATION { get; set; }
    public string COMPUTER_NAME { get; set; }
    public string OS_LICENSE { get; set; }
    public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USERID { get; set; }
    public Nullable<int> COMPANY_ID { get; set; }
    public string USER_NAME { get; set; }
    public string EMAIL { get; set; }
    public Nullable<int> FK_LICENSE__ID { get; set; }
    public string LIC_NAME { get; set; }
    public string DEVICE_MAC { get; set; }
    public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
}

public partial class V_SYSTEM_MEMORY
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USER_ID { get; set; }
    public string ATTRIBUTES { get; set; }
    public string BANK_LABEL { get; set; }
    public long CAPACITY { get; set; }
    public string CAPTION { get; set; }
    public long CONFIGURE_CLOCL_SPEED { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_LOCATOR { get; set; }
    public string MANUFACTURER { get; set; }
    public string SERIAL_NO { get; set; }
    public string SPEED { get; set; }
    public string NAME { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string COMPUTER_NAME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public string LOGIN_NAME { get; set; }
}

public partial class V_SYSTEM_MEMORY_INFO
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string ATTRIBUTES { get; set; }
    public long CAPACITY { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_LOCATOR { get; set; }
    public string MANUFACTURER { get; set; }
    public string SPEED { get; set; }
    public string NAME { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string COMPUTER_NAME { get; set; }
    public int USERID { get; set; }
}

public partial class V_SYSTEM_MEMORY_USAGE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USER_ID { get; set; }
    public string USAGE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string COMPUTER_NAME { get; set; }
    public int USERID { get; set; }
    public string PHYSICAL_RAM_MEMORY { get; set; }
}

public partial class V_SYSTEM_NETWOR_DEVICES
{
    public long SYSTEM_ID { get; set; }
    public long ID { get; set; }
    public string DESCRIPTION { get; set; }
    public string NAME { get; set; }
    public Nullable<System.DateTime> TIME_STAMP { get; set; }
    public string STATUS { get; set; }
    public string SPEED { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string COMPUTER_NAME { get; set; }
    public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USERID { get; set; }
}

public partial class V_SYSTEM_NETWORK
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string DESCRIPTION { get; set; }
    public string NAME { get; set; }
    public string STATUS { get; set; }
    public string SPEED { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public string LOGIN_NAME { get; set; }
    public int USER_ID { get; set; }
}

public partial class V_SYSTEM_POINTING_DEVICE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string DEVICE_INTERFACE { get; set; }
    public string MANUFACTURER { get; set; }
    public string NAME { get; set; }
    public string SYSTEM_NAME { get; set; }
    public long Expr1 { get; set; }
    public string MAC_ADDRESS { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string COMPANY { get; set; }
    public int USERID { get; set; }
}

public partial class V_SYSTEM_PORTS_CONNECTOR
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string CONNECTOR_TYPE { get; set; }
    public string DESCRIPTION { get; set; }
    public string NAME { get; set; }
    public string TAG { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string COMPANY { get; set; }
    public int USERID { get; set; }
}

public partial class V_SYSTEM_PRINTER_INFORMATION
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string NAME { get; set; }
    public Nullable<int> HORIZONTAL_RESOLUTION { get; set; }
    public Nullable<int> VERTICAL_RESOLUTION { get; set; }
    public Nullable<bool> NETWORK { get; set; }
    public string PRINTER_PAPER_NAME { get; set; }
    public string PAPER_SIZE_SUPPORTED { get; set; }
    public string SYSTEM_NAME { get; set; }
    public string STATUS { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string COMPANY { get; set; }
    public int USERID { get; set; }
}

public partial class V_SYSTEM_PROCESSOR_USAGE
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public int USER_ID { get; set; }
    public string USAGE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string COMPUTER_NAME { get; set; }
    public int USERID { get; set; }
    public string CPU_SPEED_IN_GHZ { get; set; }
}

public partial class V_SYSTEM_REGISTERED_APPS
{
    public long ID { get; set; }
    public string APP_NAME { get; set; }
    public long SIZE { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string COMPUTER_NAME { get; set; }
    public int USERID { get; set; }
    public string MOTHERBOARD_MANUFACTURER { get; set; }
    public long SYSTEM_ID { get; set; }
}

public partial class V_SYSTEM_SOUND
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string MANUFACTURER { get; set; }
    public string NAME { get; set; }
    public string SYSTEM_NAME { get; set; }
    public string MAC_ADDRESS { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string COMPANY { get; set; }
}

public partial class V_SYSTEM_SOUND_DEVICES
{
    public long ID { get; set; }
    public long SYSTEM_ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string MANUFACTURER { get; set; }
    public string NAME { get; set; }
    public string STATUS_INFO { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string MOTHERBOARD_MANUFACTURER { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string COMPUTER_NAME { get; set; }
    public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USERID { get; set; }
}

public partial class V_SYSTEM_VIDEO_CONTROLLER
{
    public long ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public string NAME { get; set; }
    public string VIDEO_ARCHITECTURE { get; set; }
    public string VIDEO_PROCESSOR { get; set; }
    public string VIDEO_MEMORY_TYPE { get; set; }
    public long SYSTEM_ID { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string COMPANY { get; set; }
}

public partial class V_SYSTEM_VIDEO_CONTROLLERS
{
    public long SYSTEM_ID { get; set; }
    public long ID { get; set; }
    public string CAPTION { get; set; }
    public string DESCRIPTION { get; set; }
    public Nullable<System.DateTime> DRIVER_DATE { get; set; }
    public string DRIVER_VERSION { get; set; }
    public string NAME { get; set; }
    public string VIDEO_ARCHITECTURE { get; set; }
    public string VIDEO_PROCESSOR { get; set; }
    public string MAC_ADDRESS { get; set; }
    public long Expr1 { get; set; }
    public string MOTHERBOARD_MANUFACTURER { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public string DEFAULT_IP_GATEWAY { get; set; }
    public string COMPUTER_NAME { get; set; }
    public Nullable<System.DateTime> LAST_BOOT_TIME { get; set; }
    public int USERID { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
}

public partial class V_SYSTEM_VOLUME
{
    public int Expr1 { get; set; }
    public long SYETEM_ID { get; set; }
    public string DEVICE_TYPE { get; set; }
    public string CAPTION { get; set; }
    public string SERIAL_NO { get; set; }
    public string TOTAL { get; set; }
    public string FREE { get; set; }
    public string USED { get; set; }
    public string MAC_ADDRESS { get; set; }
    public string ACCOUNT_NAME { get; set; }
    public Nullable<System.DateTime> SYSTEM_UP_TIME { get; set; }
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string COMPANY { get; set; }
}

public partial class V_USER_LOGIN_DETAIL
{
    public int USER_ID { get; set; }
    public string LOGIN_NAME { get; set; }
    public string PASSWORD { get; set; }
    public string EMAIL { get; set; }
    public Nullable<int> USER_ROLE { get; set; }
    public Nullable<bool> STATUS { get; set; }
    public string COMPANY { get; set; }
    public string FIRST_NAME { get; set; }
    public string LAST_NAME { get; set; }
    public string PHONE { get; set; }
    public Nullable<System.DateTime> LAST_LOGIN { get; set; }
    public bool EMAIL_ALERT { get; set; }
    public bool SMS_ALERT { get; set; }
    public bool PHONE_ALERT { get; set; }
    public string ADDRESS_LINE_1 { get; set; }
    public string ADDRESS_LINE_2 { get; set; }
    public string STATE { get; set; }
    public string CITY { get; set; }
    public string PINCODE { get; set; }
    public string COUNTRY { get; set; }
    public string MAC_ADDRESS { get; set; }
    public long SYSTEM_ID { get; set; }
    public Nullable<int> FK_COMPANY_ID { get; set; }
}

public partial class V_USER_PRIVS_WITHROLE
{
    public int PRIVID { get; set; }
    public string DEFAULTNAME { get; set; }
    public string DEFUULTTEXT { get; set; }
    public bool STATUS { get; set; }
    public string ROLENAME { get; set; }
    public int ROLEID { get; set; }
    public int USER_ID { get; set; }
}

public partial class WINDOW_ACTIVE
{
    public int ID { get; set; }
    public Nullable<long> SYSTEM_ID { get; set; }
    public string WINDOW_TITLE { get; set; }
    public System.DateTime TIME_STAMP { get; set; }
    public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    public string WIN_PROCESS { get; set; }
    public string WINDOW_URL { get; set; }
    public Nullable<long> VISIT_COUNT { get; set; }
    public long SECONDS { get; set; }
    public Nullable<System.DateTime> START_TIME { get; set; }
    public Nullable<System.DateTime> END_TIME { get; set; }

    public virtual SYSTEM_INFORMATION SYSTEM_INFORMATION { get; set; }
}
